coverage:
  status:
    project:
      default:
        target: 95%

ignore:
  - "cmd/**/*"
  - "internal/container/**/*"
  - "internal/handlers/routes.go"
  # Infrastructure stores tested via integration tests
  - "internal/store/redis.go"
  - "internal/store/postgres.go"
  - "internal/store/redis_cache.go"
